name: doctor
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-244.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: any
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.3.10
  path: ^1.8.3
  dotted_border: ^2.0.0+3
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  mongo_dart:
  image: ^4.0.15
  cloud_firestore: ^4.15.3
  intl: ^0.19.0
  flutter_iconly: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#ffffff"
  image: assets/SplashScreen.png
  android_gravity: fill
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

